Add service implementation and write unit/integration tests
DenKorporation/Autopark_AuthorizationService pull request #2
Opened 2024-10-07 08:18 UTC by DenKorporation

2024-10-17 13:44 UTC, TarasovaVeronika requested changes

2024-10-17 13:44 UTC, TarasovaVeronika commented on src/AuthorizationService.BLL/Services/Implementations/ContractService.cs
> +    public async Task<Result<ContractResponse>> CreateAsync(
Should we return the result in service methods?

2024-10-18 08:53 UTC, DenKorporation commented on src/AuthorizationService.BLL/Services/Implementations/ContractService.cs
> +    public async Task<Result<ContractResponse>> CreateAsync(
I use result pattern to avoid exception. This result class is taken from FluentResults package.

2024-10-22 06:48 UTC, TarasovaVeronika approved these changes

2024-10-22 07:04 UTC, merged